---
# Operator: opentelemetry-product
# Full Name: opentelemetry-product.openshift-opentelemetry-operator
# CRD Patterns: opentelemetry.io
# Note: Uninstalling this operator will delete all CRDs matching the above patterns
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: ${NAMESPACE}-
  namespace: ${NAMESPACE}
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: opentelemetry-product
  namespace: ${NAMESPACE}
spec:
  channel: stable
  name: opentelemetry-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
